#ifndef EXTriggerRegisterPlayerUnitDamagedEventIncluded
#define EXTriggerRegisterPlayerUnitDamagedEventIncluded

native EXTriggerRegisterPlayerUnitDamagedEvent takes trigger whichTrigger, player whichPlayer returns event

#endif  // EXTriggerRegisterPlayerUnitDamagedEventIncluded
